// This file will be auto-generated by Supabase CLI in the future
// For now, we'll define basic types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

import { Portfolio, PortfolioType } from './portfolio'
import { Note } from './note'

export interface Database {
  public: {
    Tables: {
      portfolios: {
        Row: Portfolio
        Insert: Omit<Portfolio, 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Omit<Portfolio, 'id' | 'created_at' | 'updated_at'>>
      }
      notes: {
        Row: Note
        Insert: Omit<Note, 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Omit<Note, 'id' | 'created_at' | 'updated_at'>>
      }
      // Add your table types here when you create them in Supabase
    }
    Views: {
      // Add your view types here
    }
    Functions: {
      // Add your function types here
    }
    Enums: {
      portfolio_type: PortfolioType
      // Add your enum types here
    }
  }
}

